# Generated by Django 2.2.4 on 2020-01-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_repeated',
            field=models.BooleanField(default=False),
        ),
    ]
